# Generated by Django 5.1.1 on 2024-09-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_favoritebook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebook',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
